filebeat.inputs:
- type: container
  enabled: true
  paths:
    - /var/log/containers/*.log
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"

- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log
  fields:
    service: nginx
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - /var/log/php/*.log
  fields:
    service: php-fpm
  fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 2
  permissions: 0644
