input {
  beats {
    port => 5044
  }
}

filter {
  if [service] == "nginx" {
    grok {
      match => { "message" => "%{IPORHOST:client_ip} - %{DATA:user} \[%{HTTPDATE:timestamp}\] \"%{WORD:method} %{DATA:request} HTTP/%{NUMBER:http_version}\" %{NUMBER:response_code} %{NUMBER:body_bytes} \"%{DATA:referrer}\" \"%{DATA:user_agent}\"" }
      add_tag => ["nginx_access"]
    }
    date {
      match => ["timestamp", "dd/MMM/yyyy:HH:mm:ss Z"]
      target => "@timestamp"
    }
    mutate {
      convert => { "response_code" => "integer" }
      convert => { "body_bytes" => "integer" }
    }
  } else {
    mutate {
      add_tag => ["other_log"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "lnmp-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
